// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/verify/argo/events": {
            "post": {
                "description": "由 Argo 或外部发布观察器回写 Release 级状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verify"
                ],
                "summary": "回写发布状态",
                "parameters": [
                    {
                        "description": "Release Status Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.VerifyReleaseStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/verify/healthz": {
            "get": {
                "tags": [
                    "Verify"
                ],
                "summary": "Verify Service 健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/verify/release/steps": {
            "post": {
                "description": "由 Argo Application / Deployment / Rollout 观察器回写 Release steps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verify"
                ],
                "summary": "回写发布步骤",
                "parameters": [
                    {
                        "description": "Release Step Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.VerifyReleaseStepRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/verify/tekton/events": {
            "post": {
                "description": "由 Tekton 或外部构建观察器回写 Manifest 级状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verify"
                ],
                "summary": "回写构建状态",
                "parameters": [
                    {
                        "description": "Build Status Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.VerifyBuildStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/verify/tekton/steps": {
            "post": {
                "description": "由 Tekton TaskRun 观察器回写 Manifest steps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verify"
                ],
                "summary": "回写构建步骤",
                "parameters": [
                    {
                        "description": "Build Step Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.VerifyBuildStepRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.VerifyBuildStatusRequest": {
            "type": "object",
            "required": [
                "manifest_id",
                "status"
            ],
            "properties": {
                "external_ref": {
                    "type": "string"
                },
                "intent_id": {
                    "type": "string"
                },
                "manifest_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "pipeline_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.ManifestStatus"
                }
            }
        },
        "api.VerifyBuildStepRequest": {
            "type": "object",
            "required": [
                "manifest_id",
                "status",
                "task_name"
            ],
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "manifest_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "pipeline_id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.StepStatus"
                },
                "task_name": {
                    "type": "string"
                },
                "task_run": {
                    "type": "string"
                }
            }
        },
        "api.VerifyReleaseStatusRequest": {
            "type": "object",
            "required": [
                "release_id",
                "status"
            ],
            "properties": {
                "external_ref": {
                    "type": "string"
                },
                "intent_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "release_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.ReleaseStatus"
                }
            }
        },
        "api.VerifyReleaseStepRequest": {
            "type": "object",
            "required": [
                "release_id",
                "status",
                "step_name"
            ],
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "release_id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.StepStatus"
                },
                "step_name": {
                    "type": "string"
                }
            }
        },
        "model.ManifestStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed"
            ],
            "x-enum-varnames": [
                "ManifestPending",
                "ManifestRunning",
                "ManifestSucceeded",
                "ManifestFailed"
            ]
        },
        "model.ReleaseStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed",
                "RollingBack",
                "RolledBack",
                "Syncing",
                "SyncFailed"
            ],
            "x-enum-varnames": [
                "ReleasePending",
                "ReleaseRunning",
                "ReleaseSucceeded",
                "ReleaseFailed",
                "ReleaseRollingBack",
                "ReleaseRolledBack",
                "ReleaseSyncing",
                "ReleaseSyncFailed"
            ]
        },
        "model.StepStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed"
            ],
            "x-enum-varnames": [
                "StepPending",
                "StepRunning",
                "StepSucceeded",
                "StepFailed"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
