// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/applications": {
            "get": {
                "tags": [
                    "Application"
                ],
                "summary": "获取应用列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Application"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的应用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Application"
                ],
                "summary": "创建应用",
                "parameters": [
                    {
                        "description": "Application Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Application"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.CreateResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/applications/{id}": {
            "get": {
                "tags": [
                    "Application"
                ],
                "summary": "获取应用",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Application"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Application"
                ],
                "summary": "更新应用",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Application Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Application"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Application"
                ],
                "summary": "删除应用",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/applications/{id}/active_manifest": {
            "patch": {
                "tags": [
                    "Application"
                ],
                "summary": "更新应用的 Active Manifest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Active Manifest Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_api.UpdateActiveManifestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/configurations": {
            "get": {
                "tags": [
                    "Configuration"
                ],
                "summary": "获取配置列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Configuration"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuration"
                ],
                "summary": "创建配置",
                "parameters": [
                    {
                        "description": "Configuration Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Configuration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.CreateResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/configurations/{id}": {
            "get": {
                "tags": [
                    "Configuration"
                ],
                "summary": "获取配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configuration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Configuration"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Configuration"
                ],
                "summary": "更新配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configuration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Configuration Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Configuration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Configuration"
                ],
                "summary": "删除配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configuration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/intents": {
            "get": {
                "description": "按 kind、status、resource、application 等维度查询 execution intents",
                "tags": [
                    "Intent"
                ],
                "summary": "获取执行意图列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Intent"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/intents/{id}": {
            "get": {
                "tags": [
                    "Intent"
                ],
                "summary": "获取执行意图",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Intent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Intent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/jobs": {
            "get": {
                "tags": [
                    "Job"
                ],
                "summary": "获取Job列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Job"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的Job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "创建Job",
                "parameters": [
                    {
                        "description": "Job Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Job"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.CreateResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs/{id}": {
            "get": {
                "tags": [
                    "Job"
                ],
                "summary": "获取Job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Job"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Job"
                ],
                "summary": "更新Job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Job Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Job"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Job"
                ],
                "summary": "删除Job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/manifests": {
            "get": {
                "tags": [
                    "Manifest"
                ],
                "summary": "获取应用列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Manifest"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "根据 Manifest 创建 Manifest，自动生成名称",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manifest"
                ],
                "summary": "创建 Manifest",
                "parameters": [
                    {
                        "description": "Manifest 数据（branch 必填）",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Manifest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.CreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/manifests/{id}": {
            "get": {
                "tags": [
                    "Manifest"
                ],
                "summary": "获取应用",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Manifest ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Manifest"
                        }
                    }
                }
            },
            "patch": {
                "description": "部分更新 Manifest（仅支持 digest / commit_hash）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manifest"
                ],
                "summary": "Patch Manifest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Manifest ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patch 数据",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.PatchManifestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/projects": {
            "get": {
                "tags": [
                    "Project"
                ],
                "summary": "获取项目列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Project"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "创建项目",
                "parameters": [
                    {
                        "description": "Project Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Project"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api.CreateResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{id}": {
            "get": {
                "tags": [
                    "Project"
                ],
                "summary": "获取项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Project"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Project"
                ],
                "summary": "更新项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Project Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Project"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Project"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{id}/applications": {
            "get": {
                "tags": [
                    "Project"
                ],
                "summary": "获取项目下的应用列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Application"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/verify/argo/events": {
            "post": {
                "description": "由 Argo 或外部发布观察器回写 Job 级状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verify"
                ],
                "summary": "回写发布状态",
                "parameters": [
                    {
                        "description": "Release Status Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_api.VerifyReleaseStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/verify/healthz": {
            "get": {
                "tags": [
                    "Verify"
                ],
                "summary": "Verify Service 健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/verify/release/steps": {
            "post": {
                "description": "由 Argo Application / Deployment / Rollout 观察器回写 Job steps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verify"
                ],
                "summary": "回写发布步骤",
                "parameters": [
                    {
                        "description": "Release Step Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_api.VerifyReleaseStepRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/verify/tekton/events": {
            "post": {
                "description": "由 Tekton 或外部构建观察器回写 Manifest 级状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verify"
                ],
                "summary": "回写构建状态",
                "parameters": [
                    {
                        "description": "Build Status Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_api.VerifyBuildStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/verify/tekton/steps": {
            "post": {
                "description": "由 Tekton TaskRun 观察器回写 Manifest steps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verify"
                ],
                "summary": "回写构建步骤",
                "parameters": [
                    {
                        "description": "Build Step Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_api.VerifyBuildStepRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_bsonger_devflow-verify-service_pkg_model.Application": {
            "type": "object",
            "properties": {
                "active_manifest_id": {
                    "type": "string"
                },
                "active_manifest_name": {
                    "type": "string"
                },
                "config_maps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.ConfigMap"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "envs": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.EnvVar"
                        }
                    }
                },
                "id": {
                    "type": "string"
                },
                "internet": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Internet"
                },
                "name": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "project_name": {
                    "type": "string"
                },
                "replica": {
                    "type": "integer"
                },
                "repo_url": {
                    "type": "string"
                },
                "service": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Service"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.ReleaseType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.ConfigMap": {
            "type": "object",
            "properties": {
                "files_path": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "mount_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.Configuration": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.File"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.EnvVar": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.File": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.Intent": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "string"
                },
                "application_name": {
                    "type": "string"
                },
                "attempt_count": {
                    "type": "integer"
                },
                "branch": {
                    "type": "string"
                },
                "claimed_at": {
                    "type": "string"
                },
                "claimed_by": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "external_ref": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "job_type": {
                    "type": "string"
                },
                "kind": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.IntentKind"
                },
                "last_error": {
                    "type": "string"
                },
                "lease_expires_at": {
                    "type": "string"
                },
                "manifest_id": {
                    "type": "string"
                },
                "manifest_name": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "repo_url": {
                    "type": "string"
                },
                "resource_id": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.IntentStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.IntentKind": {
            "type": "string",
            "enum": [
                "build",
                "release"
            ],
            "x-enum-varnames": [
                "IntentKindBuild",
                "IntentKindRelease"
            ]
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.IntentStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed"
            ],
            "x-enum-varnames": [
                "IntentPending",
                "IntentRunning",
                "IntentSucceeded",
                "IntentFailed"
            ]
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.Internet": {
            "type": "string",
            "enum": [
                "internal",
                "external"
            ],
            "x-enum-varnames": [
                "Internal",
                "External"
            ]
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.Job": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "string"
                },
                "application_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "execution_intent_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "manifest_id": {
                    "type": "string"
                },
                "manifest_name": {
                    "type": "string"
                },
                "project_name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.JobStatus"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.JobStep"
                    }
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.JobStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed",
                "RollingBack",
                "RolledBack",
                "Syncing",
                "SyncFailed"
            ],
            "x-enum-varnames": [
                "JobPending",
                "JobRunning",
                "JobSucceeded",
                "JobFailed",
                "JobRollingBack",
                "JobRolledBack",
                "JobSyncing",
                "JobSyncFailed"
            ]
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.JobStep": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.StepStatus"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.Manifest": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "string"
                },
                "application_name": {
                    "type": "string"
                },
                "branch": {
                    "type": "string"
                },
                "commit_hash": {
                    "type": "string"
                },
                "config_maps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.ConfigMap"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "digest": {
                    "type": "string"
                },
                "envs": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.EnvVar"
                        }
                    }
                },
                "execution_intent_id": {
                    "type": "string"
                },
                "git_repo": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "internet": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Internet"
                },
                "name": {
                    "type": "string"
                },
                "pipeline_id": {
                    "type": "string"
                },
                "replica": {
                    "type": "integer"
                },
                "service": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Service"
                },
                "status": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.ManifestStatus"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.ManifestStep"
                    }
                },
                "type": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.ReleaseType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.ManifestStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed"
            ],
            "x-enum-varnames": [
                "ManifestPending",
                "ManifestRunning",
                "ManifestSucceeded",
                "ManifestFailed"
            ]
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.ManifestStep": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.StepStatus"
                },
                "task_name": {
                    "type": "string"
                },
                "task_run": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.PatchManifestRequest": {
            "type": "object",
            "properties": {
                "commit_hash": {
                    "type": "string"
                },
                "digest": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.Port": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "target_port": {
                    "type": "integer"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.Project": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.ProjectStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.ProjectStatus": {
            "type": "string",
            "enum": [
                "active",
                "archived"
            ],
            "x-enum-varnames": [
                "ProjectActive",
                "ProjectArchived"
            ]
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.ReleaseType": {
            "type": "string",
            "enum": [
                "normal",
                "canary",
                "blue-green"
            ],
            "x-enum-varnames": [
                "Normal",
                "Canary",
                "BlueGreen"
            ]
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.Service": {
            "type": "object",
            "properties": {
                "ports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.Port"
                    }
                }
            }
        },
        "github_com_bsonger_devflow-verify-service_pkg_model.StepStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed"
            ],
            "x-enum-varnames": [
                "StepPending",
                "StepRunning",
                "StepSucceeded",
                "StepFailed"
            ]
        },
        "pkg_api.CreateResponse": {
            "type": "object",
            "properties": {
                "execution_intent_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "pkg_api.UpdateActiveManifestRequest": {
            "type": "object",
            "required": [
                "manifest_id"
            ],
            "properties": {
                "manifest_id": {
                    "type": "string"
                }
            }
        },
        "pkg_api.VerifyBuildStatusRequest": {
            "type": "object",
            "required": [
                "manifest_id",
                "status"
            ],
            "properties": {
                "external_ref": {
                    "type": "string"
                },
                "intent_id": {
                    "type": "string"
                },
                "manifest_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "pipeline_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.ManifestStatus"
                }
            }
        },
        "pkg_api.VerifyBuildStepRequest": {
            "type": "object",
            "required": [
                "manifest_id",
                "status",
                "task_name"
            ],
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "manifest_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "pipeline_id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.StepStatus"
                },
                "task_name": {
                    "type": "string"
                },
                "task_run": {
                    "type": "string"
                }
            }
        },
        "pkg_api.VerifyReleaseStatusRequest": {
            "type": "object",
            "required": [
                "job_id",
                "status"
            ],
            "properties": {
                "external_ref": {
                    "type": "string"
                },
                "intent_id": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.JobStatus"
                }
            }
        },
        "pkg_api.VerifyReleaseStepRequest": {
            "type": "object",
            "required": [
                "job_id",
                "status",
                "step_name"
            ],
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_bsonger_devflow-verify-service_pkg_model.StepStatus"
                },
                "step_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
